# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Leave Manager.xcworkspace", scheme: "Leave Manager")
  end
  lane :beta do
    # Increment build number in XCode
    increment_build_number
    # Build your app
    gym(verbose: true)
    # Upload to TestFlight
    testflight
  end
  lane :release do
    increment_build_number
    # Run cocoapods install, commented: as this will wipe my NMessenger changes
    # cocoapods
    # Run tests
    scan
    # Take screenshots
    snapshot
    # Provisioning
    sigh
    # Upload app, screenshots and meta-data
    deliver
    # Run your own custom script
    # sh "./customScript.sh"
    # Notify your contacts on Slack
    # slack
  end
end

